swagger: "2.0"
info:
  title: "Yandex Direct Ecom API Documentation"
  contact:
    email: "s.fedyushin@ecomru.ru"
  basePath: "/swagger"
paths:
  "/yandexdirect/forecastasync/<task_id>":
    get:
tags:
  - forecasts
#    - info
summary: "Возвращает прогноз показов, кликов и затрат"
description: "Метод для получения прогноза показов, кликов и затрат"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: path
  name: task_id
  required: true
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"