swagger: "2.0"
info:
  title: "Yandex Direct Ecom API Documentation"
  contact:
    email: "s.fedyushin@ecomru.ru"
  basePath: "/swagger"
paths:
  "/yandexdirect/getbusinessprofiles":
    post:
tags:
  - info
summary: "Получить данные профилей организаций рекламодателя на Яндексе"
description: "Метод возвращает данные профилей организаций рекламодателя на Яндексе"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  required: true
  schema:
    type: "object"
    properties:
      login:
        type: "string"
        example: "aaabbbq123@yandex.ru"
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"


