swagger: "2.0"
info:
  title: "Yandex Direct Ecom API Documentation"
  contact:
    email: "s.fedyushin@ecomru.ru"
  basePath: "/swagger"
paths:
  "/yandexdirect/getaddadtextadparams":
    get:
tags:
  - params
summary: "Получить из БД параметры полей для создания текстово-графического объявления"
description: "Метод для получения из БД параметров полей для создания текстово-графического объявления"
consumes:
- "application/json"
produces:
- "application/json"
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"