swagger: "2.0"
info:
  title: "Yandex Direct Ecom API Documentation"
  contact:
    email: "s.fedyushin@ecomru.ru"
  basePath: "/swagger"
paths:
  "/yandexdirect/gethtmlbyurl/url=<path:url>":
    get:
tags:
  - url
summary: "Перейти по ссылке"
description: "Перейти по ссылке в адресе"
#consumes:
#- "application/json"
#produces:
#- "application/json"
parameters:
- in: path
  name: url
  required: true
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"